### ISSUE TITLE
Sequential objects accumulate values.

### ISSUE THREAD

**Issue by Bardo91** [technik/cjson#10]
For example:

	Json foo;
	foo.parse(R"({"x":{"x1":1, "x2":2}, "y":{"y1":4, "y2":5}})");

Throw this output:

	{
		"x":    {
			"x1":           1,
			"x2":           2
        		},
		"y":    {
			"x1":           1,
			"x2":           2,
			"y1":           4,
			"y2":           5
		}
	}

This is caused by reusing `Json value` variable in `parser.cpp:166`. Moving this two lines forward solve the error. 

**New Output**:

	{
		"x":    {
			"x1":           1,
			"x2":           2
        		},
		"y":    {
			"y1":           4,
			"y2":           5
		}
	}

**Comment by technik** [comment]
Added a test case and solved it.
