### ISSUE TITLE
Fail while parsing an object that has an array of objects.

### ISSUE THREAD

**Issue by Bardo91** [technik/cjson#12]
Parser returns a valid json but wrongly parsed.

	{
		"metadata":
		{
			"numObjects":8,
			"numLabels":3,
			"labels":[0,1,2]
		},
		"data":
		[
			{
				"name":"Crawler",
				"label":2,
				"position":
				{
					"x":0.371,
					"y":-0.319,
					"z":1.166
				},
				"dimension":
				{
					"width":0.235,
					"height":0.169,
					"depth":0.204
				}
			},
			{
				"name":"Circuit_1",
				"label":1,
				"position":
				{
					"x":0.532,
					"y":0.034,
					"z":1.112
				},
				"dimension":
				{
					"width":0.047,
					"height":0.033,
					"depth":0.066
				}
			},
			{
				"name":"Circuit_2",
				"label":1,
				"position":
				{
					"x":0.297,
					"y":-0.067,
					"z":1.193
				},
				"dimension":
				{
					"width":0.105,
					"height":0.028,
					"depth":0.068
				}
			},
			{
				"name":"Circuit_3",
				"label":1,
				"position":
				{
					"x":0.16,
					"y":0.107,
					"z":1.189
				},
				"dimension":
				{
					"width":0.093,
					"height":0.042,
					"depth":0.09
				}
			},
			{
				"name":"Circuit_4",
				"label":1,
				"position":
				{
					"x":0.056,
					"y":-0.233,
					"z":1.273
				},
				"dimension":
				{
					"width":0.054,
					"height":0.023,
					"depth":0.061
				}
			},
			{
				"name":"Circuit_5",
				"label":1,
				"position":
				{
					"x":-0.108,
					"y":0.095,
					"z":1.264
				},
				"dimension":
				{
					"width":0.063,
					"height":0.029,
					"depth":0.079
				}
			},
			{
				"name":"Circuit_6",
				"label":1,
				"position":
				{
					"x":-0.017,
					"y":-0.073,
					"z":1.255
				},
				"dimension":
				{
					"width":0.70,
					"height":0.031,
					"depth":0.07
				}
			},
			{
				"name":"Battery",
				"label":0,
				"position":
				{
					"x":-0.11,
					"y":-0.320,
					"z":1.322
				},
				"dimension":
				{
					"width":0.035,
					"height":0.021,
					"depth":0.09
				}
			}
		]
	}

**Comment by Bardo91** [comment]
The error is that it cannot parse negative real numbers. so inside:

            "position":
            {
                "x":0.371,
                "y":-0.319,
                "z":1.166
            }

It stops at "y" key and return an invalid number.

**Comment by Bardo91** [comment]
The error is that while parsing numbers '+' and '-' characters are not added to `digits`string. So while looking for dot character ('.') it stops at the beginning ('-' in this case)

	const std::string digits("+-0123456789");
	int c;
	while(digits.find(mIn->peek()) != std::string::npos)
		c = mIn->get();

A possible solution is to add this charaters to digits string (and may be change it names to digitsAndSigns or something). Or create another string call signs and check in both. I tested it and it works.

**Comment by technik** [comment]
Solved and added a test case.
